### ISSUE TITLE
drivers/input/touchscreen/ft5x_ts.c:884:5: error: implicit declaration of function ‘delay_ms’

### ISSUE THREAD

**Issue by dreamingdeer** [dan-and/linux-sunxi#11]
delay_ms defined in arch/arm/mach-sun7i/pm/mem_timing.c

**Comment by igorpecovnik** [comment]
I can compile the kernel without error and also using one display with this driver.

**Comment by dreamingdeer** [comment]
yes if CONFIG_PM is not set all will be ok.

**Comment by dan-and** [comment]
then let's close it.
