### ISSUE TITLE
kernel image compiling

### ISSUE THREAD

**Issue by sinadogru** [dan-and/linux-sunxi#13]
Hello,

I am trying to build kernel 3.4.108 for my A10 Lime Olimex, so I use sun4i_defconfig.

make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- sun4i_defconfig
make -j4 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage

But when I compile uImage for it, it stops compilation at a point and just before it stops it gives this warning:

fs/binfmt_misc.c: In function ‘parse_command.part.7’:
fs/binfmt_misc.c:421:7: warning: array subscript is above array bounds [-Warray-bounds]
  if (s[count-1] == '\n')
       ^

Anyone else got this warning? is there anyway to overcome?

By the way, I have that message after I make the _defconfig:

drivers/net/wireless/bcmdhd/Kconfig:42 : warning: defaults for choice values not supported
# 

# configuration written to .config
# 

Thanks,
Sina

**Comment by dan-and** [comment]
I don't support Allwinner A10 , just A20.

**Comment by rellla** [comment]
Warnings are no errors. You should provide the full log and/ or try if upstream linux-sunxi builds. Both should imho with sun4i_defconfig.
