### ISSUE TITLE
bcmdhd module build error due to `dhd_mmc_suspend' symbol

### ISSUE THREAD

**Issue by mytbk** [dan-and/linux-sunxi#15]
I just modified the code and made this patch at:
http://pastebin.com/ecYuccML

And another thing, when building bcmdhd, another error occured which says:
make[1]: **\* No rule to make target 'firmware/ap6210/bcm20710a1.hcd', needed by '__fw_modbuild'

**Comment by dan-and** [comment]
can not follow. Sorry. Please add more details
