### ISSUE TITLE
SPDIF Pass-trougth does not work

### ISSUE THREAD

**Issue by damien7851** [dan-and/linux-sunxi#18]
Hi,

I have tested #17  pull request but it s doesn't work.
see my comment in pull request

**Comment by dan-and** [comment]
I have no chance to test this at all. 
Maybe get in touch with https://github.com/nikkov to figure out your issues. 

Daniel

**Comment by damien7851** [comment]
Hi,

I have successfully tested spdif pass through with kernel 3.4.111.
