### ISSUE TITLE
Error Compiling Modules For 3.4.107

### ISSUE THREAD

**Issue by dmryce** [dan-and/linux-sunxi#23]
Building modules, stage 2.
 MODPOST 1154 modules
WARNING: drivers/net/wireless/bcmdhd/bcmdhd: 'bcmsdh_probe' exported twice. Previous export was in drivers/net/wireless/bcm4330/bcm4330.ko
WARNING: drivers/net/wireless/bcmdhd/bcmdhd: 'bcmsdh_remove' exported twice. Previous export was in drivers/net/wireless/bcm4330/bcm4330.ko
ERROR: "__modver_version_show" [drivers/staging/rts5139/rts5139.ko] undefined!
/home/dryce/Downloads/linux-sunxi-dan-3.4.106/scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[1]: **\* [__modpost] Error 1
Makefile:1098: recipe for target 'modules' failed
make: **\* [modules] Error 2

The uImage creates properly, but the modules fail. I am using gcc-linaro-arm-linux-gnueabihf toolchain to crosscompile on Arch Linux x86-64. I just tried to build the current 3.4.111 modules and it fails with the same error. The uImage builds normally.

UPDATE: Looks like running:

sed -i s/CONFIG_RTS5139=m/CONFIG_RTS5139=n/ .config

resolves this issue and allows the modules to build properly.

**Comment by dan-and** [comment]
I will have a look.

**Comment by dan-and** [comment]
I can not follow your issue. It works just fine on my systems and the module is even included in my tar builds ( http://dl.danand.de ).
