### ISSUE TITLE
3.4.103 and systemd 214 does not working

### ISSUE THREAD

**Issue by fedya** [dan-and/linux-sunxi#3]
Hi latest kernel 3.4.103 not working with systemd >213
because of need enable xattr support in kernel

Look this
http://cgit.freedesktop.org/systemd/systemd/commit/?id=d2edfae0f9bdbecf6a8518e2a5bcf06f470e0d9e&ss=1

arch linux issue
https://github.com/archlinuxarm/PKGBUILDs/issues/861

**Comment by dan-and** [comment]
Thats weird! 

Did it work with the older versions ? I have a few ARCH users and they told me that XATTR support is working (at least for the versions  <103)

**Comment by fedya** [comment]
i built branch dan-3.4.103

Did it work with the older versions ?
Not.

3.4.103 has no support XATTR in cgroups.
Xattr working fine for ext4, but not for cgroups

Look at systemd commit 
        { "cgroup",     "/sys/fs/cgroup/systemd",    "cgroup",     "none,name=systemd,xattr", MS_NOSUID|MS_NOEXEC|MS_NODEV, 

Need to implement xattr for cgroups

This guy already did it https://github.com/maggu2810/linux-kernel/wiki/cgroups-xattr-backport
But it is 3.4.90 kernel and i prefer yours.

If you gimme your pubkey
i can provide access to my cubietruck and show how to run 
lxc containter with systemd214

**Comment by fedya** [comment]
> I have a few ARCH users and they told me that XATTR support is working

They were just removed xattr option from systemd

**Comment by dan-and** [comment]
Could you retest on the 104 branch ?

**Comment by igorpecovnik** [comment]
Something is not o.k. with this build. I could not compile it with my default or even with sun7i_defconfig. Custom patched or unpatched.

 CC      lib/lzo/lzo1x_compress.o
make[2]: **\* No rule to make target `lib/lzo/lzo1x_decompress_safe.o', needed by`lib/lzo/lzo_compress.o'.  Stop.

Will check again and debug l8r.

Thanks.

**Comment by dan-and** [comment]
Igor, 

That should be fixed. lib/lzo/lzo1x_decompress_safe.c was accidental not in the last updates.

**Comment by dan-and** [comment]
It was in again with 85b989c

**Comment by igorpecovnik** [comment]
Successfully compiled! Thanks.

**Comment by fedya** [comment]
Hi, Dan.

Now all working fine!
Thanks for your help.
