### ISSUE TITLE
systemd 216 and networkd service not working with 3.4.x kernel

### ISSUE THREAD

**Issue by fedya** [dan-and/linux-sunxi#5]
My systemd-networkd service not working after systemd update from 214 to 216

Need to update kernel again
https://bugs.freedesktop.org/show_bug.cgi?id=84373
http://archlinuxarm.org/forum/viewtopic.php?f=33&t=6413&start=160#p42369

**Comment by fedya** [comment]
https://github.com/maggu2810/linux-kernel/wiki/filter-BPF-XOR-backport

**Comment by dan-and** [comment]
Working on it. Wait for the 105 uploads :)

**Comment by fedya** [comment]
Thanks

**Comment by dan-and** [comment]
Should be fixed in105 :)
