### ISSUE TITLE
Not supported r4p0 MALI driver. Easy fix available!

### ISSUE THREAD

**Issue by vanfanel** [dan-and/linux-sunxi#6]
Hi. 
This kernel seems to be stuck at r3px MALI, which is old and slow.
To support r4p0, you can backport the MALI driver from this kernel:

https://github.com/mireq/linux-sunxi

Please, do so if possible!

**Comment by dan-and** [comment]
Hi. 

I look into this. I have added it to the repo  in 104 as well as in 105. However I need to test it on my own in the next days.

**Comment by dan-and** [comment]
should be fixed in 105
