### ISSUE TITLE
mali video driver fails to build when building kernel outside of source tree

### ISSUE THREAD

**Issue by netfab** [dan-and/linux-sunxi#7]
Hi,

I'm trying to update from 3.4.103 to 3.4.105.
Usually I'm using the linux KBUILD_OUTPUT env variable to build  the kernel in another directory, to keep the original source tree clean.
In this version, Mali video driver was updated, but it fails to build if the build tree is NOT the source tree.

In short, if I do :

> cd /usr/src/linux-sunxi-3.4.105
> export KBUILD_OUTPUT="/usr/src/linux-sunxi-3.4.105/build"
> make

Then it fails like this :

>   Using /usr/src/linux-sunxi-3.4.105 as source for kernel
>  GEN     /usr/src/linux-sunxi-3.4.105/build/Makefile
>  CHK     include/linux/version.h
>  CHK     include/generated/utsrelease.h
> make[2]: 'include/generated/mach-types.h' is up to date.
>   CALL    /usr/src/linux-sunxi-3.4.105/scripts/checksyscalls.sh
>   CHK     include/generated/compile.h
>   CHK     kernel/config_data.h
> /usr/src/linux-sunxi-3.4.105/drivers/gpu/mali/mali/Kbuild:32: **\* Runtime PM is incompatible with non-GPL license. Arrêt.
> /usr/src/linux-sunxi-3.4.105/scripts/Makefile.build:443: recipe for target 'drivers/gpu/mali/mali' failed
> make[4]: **\* [drivers/gpu/mali/mali] Error 2
> /usr/src/linux-sunxi-3.4.105/scripts/Makefile.build:443: recipe for target 'drivers/gpu/mali' failed
> make[3]: **\* [drivers/gpu/mali] Error 2
> /usr/src/linux-sunxi-3.4.105/scripts/Makefile.build:443: recipe for target 'drivers/gpu' failed
> make[2]: **\* [drivers/gpu] Error 2
> /usr/src/linux-sunxi-3.4.105/Makefile:947: recipe for target 'drivers' failed
> make[1]: **\* [drivers] Error 2
> Makefile:130: recipe for target 'sub-make' failed
> make: **\* [sub-make] Error 2

Can you please transmit this to upstream, I can't find their bug tracking system. Thanks !

**Comment by dan-and** [comment]
Thats weird. It's complete on my side, but I cross-compile everything instead of waiting hours on the cubieboards to be compiled. 

Could you retry on 3.4.106 ?

**Comment by netfab** [comment]
> I cross-compile everything instead of waiting hours on the cubieboards to be compiled.

Me too.

> Could you retry on 3.4.106 ?

Same error with KBUILD_OUTPUT, but builds fine without it.

**Comment by dan-and** [comment]
pretty weird. I still have no problems building it ...
